backend:
  name: github
  repo: waspeer/klangstof-website

media_folder: static/assets
public_folder: /assets

collections:
  - name: general
    label: General
    files:
      - name: menuItems
        label: Menu Items
        file: ./src/content/menuItems.yml
        fields:
          - name: items
            label: Items
            widget: list
            fields:
              - { name: name, label: Name }
              - { name: url, label: url }
  - name: music
    label: Music
    folder: ./src/content/music
    create: true
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'image', label: 'Image', widget: 'image' }
      - { name: 'date', label: 'Release Date', widget: 'datetime', default: '', dateFormat: true }
      - { name: description, label: description }
      - name: type
        label: Type
        widget: select
        options:
          - { label: 'album', value: 'album' }
          - { label: 'single', value: 'single' }
          - { label: 'ep', value: 'ep' }
      - name: links
        label: Links
        widget: list
        fields:
          - { name: platform, label: Platform }
          - { name: url, label: Url }
