[build]
  command = "npx pnpm install -r --store=node_modules/.pnpm-store && npx pnpm build"
  ignore = "git diff --quiet HEAD^ HEAD ."
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"

[dev]
  command = "pnpm dev"
